services:
  - type: web
    name: dcc-nda-website
    env: node
    buildCommand: cd nda-website/nda-app && npm install && npm run build
    startCommand: cd nda-website/nda-app && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
