services:
  - type: web
    name: nda-app
    env: node
    plan: free
    buildCommand: npm install && NODE_OPTIONS="--max-old-space-size=1024" npm run build
    startCommand: npm run render-start
    # Add health check endpoint
    healthCheckPath: /api/health
    # Increase startup timeout
    initialDeployHook: sleep 20
    # Add auto-scaling configuration
    autoscaling:
      min: 1
      max: 1
    # Ensure static assets are properly served
    staticPublishPath: ./public
    routes:
      - type: rewrite
        source: /logo.png
        destination: /logo.png
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://dccdev123:ljIAiR09FxaZJrvv@cluster0.je4ebjs.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: nda-app
          property: url
      # Add explicit port configuration
      - key: PORT
        value: 3000
